name: Test workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout
        uses: "actions/checkout@master"

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint sources
        run: npm run lint

  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout
        uses: "actions/checkout@master"

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:coverage
        env:
          PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
          ARCHIVAL_RPC: ${{ secrets.ETHEREUM_ARCHIVAL_RPC }}
          POLYGONSCAN_API_KEY: ${{ secrets.ETHEREUM_SCAN_API_KEY }}
